### PR TITLE
Add more tags to PrimaryTagChoose blacklist

### PR DESCRIPTION
**Pull request by Freso**
All taken from chosen primary tags used on the site as of the time of this commit, except for "Singleplayer" which just seems like a natural addition next to "Multiplayer" and "Co-op".

Expanding on the list introduced with https://github.com/250/Steam-Top-250/issues/10 / commit 8f41e2b48a024f3c395e0847579f1c2f5069ccd6.

Some other tags I noted but ended up not including in this PR: Story Rich, Zombies, Difficult, Sci-fi, Anime, Space, Cute, Comedy, Open World.

### CODE REVIEW

**Comment by Bilge** [comment]
I understand the desire to exclude *Singleplayer* and maybe *Co-op*, because they're congruent with existing exclusions that apply to *number of players*. However, I cannot accept any of the other exclusions without individual justification.

**Comment by Freso** [comment]
"Great Soundtrack": not useful as a genre. If I look over top games and see Bastion, I'm more interested seeing it classified as "RPG", or "Twin Shooter", or some other actual game type, not that it has a "great soundtrack".
"Female Protagonist": Tomb Raider is an "action" or "adventure" game, not a "Female Protagonist" game.
"Nudity" and "Sexual Content": I would say that [DEEP SPACE WAIFU](http://store.steampowered.com/app/639790/DEEP_SPACE_WAIFU/) is a "shoot 'em up" game, not a "nudity" or "sexual content" game (even though those are heavily featured).
"Pixel Graphics": describes the graphics of the game, not the gameplay. [«OneShot is a surreal top down Puzzle/Adventure game with unique gameplay capabilities.»](http://store.steampowered.com/app/420530/OneShot/), it's not a "pixel graphics" game even if it has pixel graphics.
"Dark Humor": conveys the mood of the game, not the genre of the game. POSTAL 2 is an action game that employs dark humor, not a dark humor game.

IMHO.

**Comment by Freso** [comment]
"Nudity", "Sexual Content", and "Dark Humor" I can maybe see not blacklisting (similar to how I ended up not included e.g., "Cute" and "Comedy"), but I absolutely think Great Soundtrack, Fem. Protagonist, and Pixel Graphics should be.

Also, all of the ones here, except for Dark Humor, still has their own 250 tag pages for people who specifically want to find games with that quality/feature.

**Comment by Bilge** [comment]
If we want to approach this discussion constructively I think we need to be as objective as possible about how we exclude genres from the primary position. For that reason, I want to start off by apologising for not providing any justification in the code for the existing exclusions. Let me correct that now by explaining the genres we currently exclude.

* Early Access - Not a genre; release tag.
* Free to Play - Not a genre; price tag.
* Indie - Not a genre; describes financial support. Also ubiquitous tag whose overuse has devalued the term.
* Multiplayer - Not a genre; input support tag.
* RPGMaker - Not a genre; engine tag.
* VR - Not a genre; platform tag. Moreover, duplicates the platform labels already displayed.

Note that in every case we have only excluded tags that are strictly not genres as they apply to the game's content. However, I think most of your proposed exclusions *are* genres. 

If I may say, I think the problem is you have a preference for *classical* genres like *action*, *puzzle*, *adventure*, *racing* and *RPG* and reject some of the newer and more specialized classifications such as *Dark Humor* and *Sexual Content*. Keep in mind that tags can only appear in the primary position if they are the tag most applied to that game (indicating most people feel it's suitable). Let's consider a few examples.

POSTAL 2 is very much a comedy game and it certainly is dark comedy, so the *Dark Humour* tag isn't just accurate, it's probably the *most accurate* tag to describe the type of game. Ergo it's correct and certainly should not be excluded.

Although DEEP SPACE WAIFU is a shooter, it's a game about nudity *first* and shooting *second*. As far as shooters go, it's fairly basic and underdeveloped. The focus is on stripping down girls. Ergo it's correct and certainly should not be excluded.

Although Bastion is an action game, one of the most talked about and acclaimed aspects of its success is its sound track, above all else. As such, it's one of the few cases where *Great Soundtrack* has been applied more than any other tag, and as such it's a perfectly valid primary tag to be distinguish it by. And to be clear, according to your proposed exclusions, the tag that would be displayed instead is *Action*, since it is the next most popular, not *RPG* or *Twin Shooter*.

The only tag I have any doubts about is *Pixel Graphics*. On one hand, if that's the tag people feel most strongly about for a particular game then perhaps that is its most defining feature. But on the other, perhaps graphics style is not really a good primary tag because it's too vague. All games have some form of graphics, and there's nothing particularly defining about being 2D, 3D, pixel graphics, or whatever; they're all very common. I could be persuaded one way or the other about graphics tags, but if we're going to exclude one we need to exclude them all, including *2D* and any [others](https://steamdb.info/tags/).

But certainly *Singleplayer* and *Co-op* fit our existing exclusion rules.

**Comment by Freso** [comment]
As I said, I'm on the fence about some of them, and you've convinced back to the current side of the fence for them. I still don't agree with "great soundtrack" though. :man_shrugging: 

You didn't mention why you don't (or do!) agree with "Female Protagonist"…?

I will split up the PR into multiple more thematic commits; one for "gameplay modes" and one for "graphics". Do you want all tags included even if they don't currently appear as the top tag of any games on the site (e.g., "Crowdfunded", "Local Multiplayer", "Massively Multiplayer", "4 Player Local", …)?

PS. I don't have "a preference for classical genres" per se, I just don't think anything can be neatly fit into one classifier (which I guess is why Steam has plural "tags" and not singular "genre"). It is not clear what kind of classifier is wanted for the site; whether it is mood (dark humor, cute), game genre (action, RPG), literary genre (sci-fi, fantasy), theme (mental illness, family life), setting/environment (underwater, jungle), graphical style (text based, pixel graphics, hand-drawn), music style, etc. Without being stated what is wanted and not wanted, I gravitated towards going for game and literary genres, as those seems to be most prevalent as top tags for games.

**Comment by Bilge** [comment]
*Female Protagonist* is a valid genre because it describes the content of the game.

>Do you want all tags included even if they don't currently appear as the top tag of any games on the site 

I suppose we should do but I don't feel strongly about it whilst not popular enough to have any impact. We can always fix it later.

**Comment by Bilge** [comment]
Tag blacklist will be replaced by more intelligent tag categorization system.

**Pull request closed without merging**
