### PR TITLE
Check year also when deciding for relative dates

### PR DESCRIPTION
**Pull request by amcsi**
Doesn't look like you're using tests :P

### CODE REVIEW

**Comment by Bilge** [comment]
The build is the test :P

I also considered making this change, however I think it's just compounding the voodoo magic problem because we still don't know exactly how it works. From what I can tell, it will switch mode when the difference in days is greater than the number of days in the current month, which means this month it will switch at 28 days but at other times of the year it will alternative between 30/31. Which is weird.

What do you think about being explicit and just setting it to 30 days fixed throughout the year instead?

**Comment by amcsi** [comment]
@Bilge I feel like there would be an even a simpler explanation for why what you are saying: checking for whether the age is at least 30 days old documents itself better.

**Comment by amcsi** [comment]
Re: build
Usually part of the build process is running the tests :P

**Comment by Bilge** [comment]
@amcsi Could you squash so I can merge? I would do it myself but it will lose your signature.

**Comment by amcsi** [comment]
@Bilge it's okay, feel free to squash it if you'd like.

**Comment by Bilge** [comment]
Cool, your changes will be live when the build completes in 5-10 minutes.

**Comment by amcsi** [comment]
Ah yes. I've got some personal project websites that also auto-deploy like that with CI :D

**Pull request merged**
